### PR TITLE
Added a classname for the appInsights HOC's div

### LINKED ISSUE #73: Adding withAITracking will break styling for components (e.g. full width/height)
I just had an issue where I wrapped a component with `withAITracking`  for a component that was scaled to the full width and height of it's parent (`width: "100%"; height: "100%"`).

As the beta now wraps the componet in a `div` element for the tracking, and this `div` is unstyled, the resulting wrapped component no longer fills the screen.

### PR DESCRIPTION
**Pull request by florianchevallier**
Just a way to fix #73

### CODE REVIEW

**Comment by florianchevallier** [comment]
@pviotti could you please check this PR ? Thank you

**Comment by pviotti** [comment]
Hi, sorry for the late reply. This project has been officially "adopted" by the AppInsights team, so the next version will be hosted in the ApplicationInsights-JS mono-repo, and it's currently available at this path: https://github.com/microsoft/ApplicationInsights-JS/tree/master/vNext/extensions/applicationinsights-react-js Soon we will be closing this project, deprecating the package and redirecting people to that repository.  
So I suggest to port the changes of this PR to the code in that repository.  

Regarding this PR, I'm not sure what you actually aim to solve by adding an arbitrary class name to the HoC div...

**Comment by florianchevallier** [comment]
Hi, thanks for your answer and the clarification concerning the future of this repo.

Regarding this PR, giving an arbitrary class name to the HoC div helps solving this probleme ( #73 ).
In our app, the app has a 100% height / width on the divs, but adding another div as a HoC and not beeing able to style it easily breaks the layout of my app.
If you find a way to add a dynamic class name to the HoC, it would be great, but for now, adding this name will be really enough.

**Comment by pviotti** [comment]
OK, understood. I think that adding an optional argument to the HoC function would be a cleaner solution, as proposed in this comment: https://github.com/Azure/react-appinsights/issues/73#issuecomment-479137008
I'll be closing this PR, but I encourage you to propose this change to the new codebase.
Thanks!

**Comment by florianchevallier** [comment]
> OK, understood. I think that adding an optional argument to the HoC function would be a cleaner solution, as proposed in this comment

I agree on that, but since the 2nd argument is already a component name, it will force you to use a name even if you don't need one.

I'll open the PR on the new codebase. Thank you

**Pull request closed without merging**
